services:
  # hook the datetime handler into jms serializer to convert through frontend and backend
  webforge_symfony_datetimehandler:
    class:      Webforge\Symfony\DateTimeHandler
    arguments: []
    tags: 
      - { name: jms_serializer.subscribing_handler }
      - { name: h4cc_alice_fixtures.provider }

  webforge_symfony_form_iso_8601_date_time_type:
    class: Webforge\Symfony\Form\Iso8601DateTimeType
    tags:
      - { name: form.type, alias: webforge_iso8601_date_time }

  webforge_symfony_mail_spool_command:
    class: Webforge\Symfony\Commands\MailSpoolCommand
    arguments: ["%root_directory%/files/mailspool"]
    tags:
      -  { name: console.command }

  webforge_symfony_load_fixtures_command:
    class: Webforge\Symfony\Commands\LoadFixturesCommand
    tags:
      -  { name: console.command }

  webforge_symfony_dql_query_command:
    class: Webforge\Symfony\Commands\DqlQueryCommand
    arguments: ["@doctrine"]
    tags:
      -  { name: console.command }

  # this is extended in webforgeCmsBundle as compiler pass to allow adding providers with tags
  webforge_symfony_alice_loader:
    class: Nelmio\Alice\Fixtures\Loader
    factory: ['Webforge\Doctrine\Fixtures\AliceManager', createLoader]
    arguments: [['@webforge_symfony_datetimehandler']]

  webforge_symfony_alice_manager:
    class: Webforge\Doctrine\Fixtures\AliceManager
    arguments: ['@webforge_symfony_alice_loader']