services:
  # hook the datetime handler into jms serializer to convert through frontend and backend
  webforge_symfony_datetimehandler:
    class:      Webforge\Symfony\DateTimeHandler
    arguments: []
    tags: 
      - { name: jms_serializer.subscribing_handler }
      - { name: h4cc_alice_fixtures.provider }