services:
  # hook the datetime handler into jms serializer to convert through frontend and backend
  webforge_symfony_datetimehandler:
    class:      Webforge\Symfony\DateTimeHandler
    arguments: []
    tags: 
      - { name: jms_serializer.subscribing_handler }
      - { name: h4cc_alice_fixtures.provider }

  webforge_symfony_form_iso_8601_date_time_type:
    class: Webforge\Symfony\Form\Iso8601DateTimeType
    tags:
      - { name: form.type, alias: webforge_iso8601_date_time }

  webforge_symfony_mail_spool_command:
    class: Webforge\Symfony\Commands\MailSpoolCommand
    arguments: ["%root_directory%/files/mailspool"]
    tags:
      -  { name: console.command }

  webforge_symfony_load_fixtures_command:
    class: Webforge\Symfony\Commands\LoadFixturesCommand
    arguments: [[@webforge_symfony_datetimehandler]]
    tags:
      -  { name: console.command }
